services:
  # Servicio 1: Base de Datos
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mitaringadb
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=secreto

  # Servicio 2: Tu App Web
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Le decimos que este servicio depende de que la DB arranque primero
    depends_on:
      - db
    # Variables de entorno para que Django sepa c√≥mo conectarse
    environment:
      - DB_HOST=db
      - DB_NAME=mitaringadb
      - DB_USER=usuario
      - DB_PASS=secreto

volumes:
  postgres_data: